apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
        namespace: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:latest
          ports:
            - containerPort: 7575
              name: http
          env:
            - name: AUTH_LDAP_ADMIN_GROUP
              value: admin
            - name: DEFAULT_COLOR_SCHEME
              value: dark
            - name: TZ
              value: Europe/Paris
          volumeMounts:
            - name: config
              mountPath: /app/data/configs
            - name: icons
              mountPath: /app/public/icons
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: homarr-data
        - name: config
          persistentVolumeClaim:
            claimName: homarr-config
        - name: icons
          persistentVolumeClaim:
            claimName: homarr-icons
