apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/allow-shared-ip: homarr
  labels:
    name: homarr
  name: homarr
  namespace: homarr
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.1
  selector:
    name: homarr
  ports:
    - name: http
      targetPort: http
      port: 80
