apiVersion: v1
kind: Namespace
metadata:
  name: immich
---

# ConfigMap para Immich

apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  # app data
  UPLOAD_LOCATION: ./library
  DB_DATA_LOCATION: ./postgres
  TZ: America/Argentina/Mendoza

  #redis env
  REDIS_HOSTNAME: redis-service

  # Database env
  PGDATA: /var/lib/postgresql/data/db
  DB_HOSTNAME: postgres-service
  POSTGRES_USER: postgres
  POSTGRES_DB: immich
---

# Secret para las credenciales de la base de datos
apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXNwd2Q=
  POSTGRES_PASSWORD: cG9zdGdyZXNwd2Q=
  DB_USERNAME: cG9zdGdyZXM=
  DB_DATABASE_NAME: aW1taWNo