apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/allow-shared-ip: immich
  name: immich-server-service
  namespace: immich
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.4
  selector:
    app: immich-server
  ports:
  - targetPort: 2283
    port: 30004
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  ports:
    - name: machine-learning
      port: 3003
      targetPort: 3003
  selector:
    app: machine-learning
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: immich
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: immich
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP